### ISSUE TITLE
Svelte browser can not resolve @iconify

### ISSUE THREAD

**Issue by malipetek** [primocms/builder#14]
Hello, maybe this is an issue with the rollup browser or something with my configuration.
I downloaded and published primo to caprover with docker image. Any idea what this might be appreciated.

`Cannot import "@iconify/svelte/dist/Icon.svelte": no matched export path was found in "pkg_name/package.json"`

<img width="946" alt="image" src="https://github.com/primocms/builder/assets/13527277/ca73e8c1-4097-4504-be17-291347fbeb5a">

<img width="953" alt="image" src="https://github.com/primocms/builder/assets/13527277/42f3d9dc-8e19-4404-ba80-b7871721db1d">

**Comment by malipetek** [comment]
Btw this is the [repo](https://github.com/malipetek/primoso) but I also see the same in local development so I don't think this is something with the production environment or deployment misconfig.

**Comment by mateomorris** [comment]
Looks like this was caused by a change in cdnjs - you can fix it by changing the import to `import Icon from '@iconify/svelte'`

I've fixed the imports in the themes, so this shouldn't be an issue for new sites going forward.

**Comment by kaechele** [comment]
Doesn't look like the themes' `primo.json` files were updated. They still contain `import Icon from '@iconify/svelte/dist/Icon.svelte'`.
I was still hitting this issue when installing primo today.

**Comment by mateomorris** [comment]
Okay - I *think* that did it. Let me know if y'all are still seeing the issue anywhere.
